# 每天6:30执行

name: Start

on:
   push:
   gollum:
#   branches:
#     - master
   schedule:
     #minute (0 - 59)
     #hour (0 - 23)
     #day of the month (1 - 31)
     #month (1 - 12 or JAN-DEC)
     #day of the week (0 - 6 or SUN-SAT)
     - cron: '*/1 * * * *'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
#        uses: joschi/setup-jdk@v1
        with:
#          java-version: 11
          java-version: 14
          java-package: jdk
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: |
          mvn compile
      - name: Run java
        env:
          BDUSS: ${{ secrets.BDUSS }}
          SCKEY: ${{ secrets.SCKEY }}
        run: |
          mvn exec:java -Dexec.mainClass="cc.chenwenxi.actions.Run" -Dexec.args="${BDUSS} ${SCKEY}"
