# 每天6:30执行

name: Start

on:
   push:
   gollum:
   schedule:
       - cron: '30 22 * * *'

jobs:
  sex8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
#        uses: joschi/setup-jdk@v1
        with:
#          java-version: 1.8
          java-version: 14
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        env:
          BDUSS: ${{ secrets.BDUSS }}
          SCKEY: ${{ secrets.SCKEY }}
        run: |
          mvn compile exec:java -Dexec.mainClass="cc.chenwenxi.actions.Run" -Dexec.args="${BDUSS} ${SCKEY}"
